version: "2"
services:
  grafana:
    image: grafana/grafana:6.3.6
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-volume:/var/lib/grafana
      - /home/vagrant/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      - /home/vagrant/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml:ro
      - /home/vagrant/mydashboard.json:/var/lib/grafana/dashboards/mydashboard.json:ro
    environment:
      INFLUXDB_DB: telegraf
      INFLUXDB_USER: "telegraf"
      INFLUXDB_USER_PASSWORD: "secretpassword"

  influxdb:
    image: influxdb:1.7.8
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - influxdb-volume:/var/lib/influxdb
    environment:
      INFLUXDB_DB: telegraf
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "secretpassword"
      INFLUXDB_USER: "telegraf"
      INFLUXDB_USER_PASSWORD: "secretpassword"
      INFLUXDB_HTTP_AUTH_ENABLED: "true"

  telegraf:
    image: telegraf:1.12.1
    container_name: telegraf
    restart: always
    ports:
      - 50007:50007
    volumes:
      - /home/vagrant/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      INFLUXDB_DB: telegraf
      INFLUXDB_USER: "telegraf"
      INFLUXDB_USER_PASSWORD: "secretpassword"

networks:
    default:
        ipam:
            config:
                - subnet: 172.31.255.0/24

volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true